### ISSUE TITLE
Over width by `<header>` and `.centering`

### ISSUE THREAD

**Issue by aKuad** [aKuad/iitomo-1of100#119]
Over width by `<header>` and `.centering` in `common.css`.

The cause may `width: 100vh` with `padding`.

```css
header {
  /* ... */

  width: 100vw;
  box-sizing: border-box;
  padding: 0.2em;
}
```

Strangely, there are cases of occurred and not occurred in same condition.

`width: 100%` may fix it.
