### ISSUE TITLE
`working-directory` not apply to `denoland/deployctl@1`

### ISSUE THREAD

**Issue by aKuad** [aKuad/iitomo-1of100#93]
```yml
    defaults:
      run:
        working-directory: src

# ...

    - name: Upload to Deno Deploy
      uses: denoland/deployctl@v1
      with:
        project: iitomo-1of100
        entrypoint: main.ts
        exclude: tests/
```

It makes file not found error. May be `with: root` is correct way.
